### ISSUE TITLE
Proper Exit?

### ISSUE THREAD

**Issue by Az-Neter** [RMNCLDYO/gemini-ai-toolkit#4]
How is it expected to close the program on CLI when done?

Closing via Ctrl+c throws a wall of errors.

This information is notably missing from the readme.

**Comment by RMNCLDYO** [comment]
> How is it expected to close the program on CLI when done?
> 
> Closing via Ctrl+c throws a wall of errors.
> 
> This information is notably missing from the readme.

Typing 'quit' or 'exit' and then hitting enter will exit the program via the CLI and wrapper.

**Comment by RMNCLDYO** [comment]
> This information is notably missing from the readme.

Noted. Will add clear instructions on how to exit the program in the ReadMe for clarity and ease of use.

Thanks Az!
