### ISSUE TITLE
Bad timing

### ISSUE THREAD

**Issue by Az-Neter** [RMNCLDYO/gemini-ai-toolkit#5]
**Describe the bug**

**To Reproduce**
1. Fresh Install

**Desktop (please complete the following information):**
 - OS: Armbian RPI4

**Additional context**
3 hours after latest commit 🤦

Error Log:
```
File "/path/gemini.py", line 488
filename = f"{str(time.time()).replace(".","_")}>{extension}"

SyntaxError: f-string: unmatched '('
```

**Comment by RMNCLDYO** [comment]
It seems as though you changed some code, the correct code should be: filename = f"{str(time.time()).replace(".","_")}.{extension}".

Please check that and try again!

**Comment by Az-Neter** [comment]
I did not change anything, I cloned your script directly from THIS repository then ran it 👎
